
title: "Tucker Capps | Astrophysicist"
description: "PhD Student | Galactic Evolution • Simulations • HPC • Outreach"
baseurl: ""
url: "https://tuckercapps.github.io"
theme: minima
author:
  name: "Tucker Capps"
  email: "capps@ou.edu"
  github: "tuckwise"
  linkedin: "tuckercapps"
  orcid: "0009-0009-1807-5397"
  university: "University of Oklahoma"

# Navigation
header_pages:
  - research.md
  - projects.md
  - outreach.md
  - cv.md

# Social links
social_links:
  - { platform: github, user_url: "https://github.com/tuckwise" }
  - { platform: linkedin, user_url: "https://linkedin.com/in/tuckercapps" }
  - { platform: orcid, user_url: "https://orcid.org/0009-0009-1807-5397" }

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-feed
